//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add belonged role.
        /// </summary>
        internal static string G_AddBelongedRole {
            get {
                return ResourceManager.GetString("G_AddBelongedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add belonged user.
        /// </summary>
        internal static string G_AddBelongedUser {
            get {
                return ResourceManager.GetString("G_AddBelongedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string G_Amount {
            get {
                return ResourceManager.GetString("G_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount(RMB).
        /// </summary>
        internal static string G_AmountInRMB {
            get {
                return ResourceManager.GetString("G_AmountInRMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append.
        /// </summary>
        internal static string G_Append {
            get {
                return ResourceManager.GetString("G_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant email.
        /// </summary>
        internal static string G_ApplicantEmail {
            get {
                return ResourceManager.GetString("G_ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant name.
        /// </summary>
        internal static string G_ApplicantName {
            get {
                return ResourceManager.GetString("G_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant phone.
        /// </summary>
        internal static string G_ApplicantPhone {
            get {
                return ResourceManager.GetString("G_ApplicantPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachements.
        /// </summary>
        internal static string G_Attachments {
            get {
                return ResourceManager.GetString("G_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments history.
        /// </summary>
        internal static string G_AttachmentsHistory {
            get {
                return ResourceManager.GetString("G_AttachmentsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to everyone.
        /// </summary>
        internal static string G_AvailableToEveryOne {
            get {
                return ResourceManager.GetString("G_AvailableToEveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg benchmark.
        /// </summary>
        internal static string G_AverageBenchmark {
            get {
                return ResourceManager.GetString("G_AverageBenchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        internal static string G_BackToList {
            get {
                return ResourceManager.GetString("G_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark memo.
        /// </summary>
        internal static string G_BenchmarkDescription {
            get {
                return ResourceManager.GetString("G_BenchmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name.
        /// </summary>
        internal static string G_BranchName {
            get {
                return ResourceManager.GetString("G_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker.
        /// </summary>
        internal static string G_Checker {
            get {
                return ResourceManager.GetString("G_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese address.
        /// </summary>
        internal static string G_ChineseAddress {
            get {
                return ResourceManager.GetString("G_ChineseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date.
        /// </summary>
        internal static string G_ChooseDate {
            get {
                return ResourceManager.GetString("G_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose next step.
        /// </summary>
        internal static string G_ChooseFlowConnection {
            get {
                return ResourceManager.GetString("G_ChooseFlowConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose owner of next step task.
        /// </summary>
        internal static string G_ChooseToNodeRole {
            get {
                return ResourceManager.GetString("G_ChooseToNodeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload attachements.
        /// </summary>
        internal static string G_ClickToUpload {
            get {
                return ResourceManager.GetString("G_ClickToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close PO.
        /// </summary>
        internal static string G_ClosePO {
            get {
                return ResourceManager.GetString("G_ClosePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close PR.
        /// </summary>
        internal static string G_ClosePR {
            get {
                return ResourceManager.GetString("G_ClosePR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string G_Code {
            get {
                return ResourceManager.GetString("G_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact administrator.
        /// </summary>
        internal static string G_ContactAdmin {
            get {
                return ResourceManager.GetString("G_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person.
        /// </summary>
        internal static string G_ContactPerson {
            get {
                return ResourceManager.GetString("G_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person mail.
        /// </summary>
        internal static string G_ContactPersonEmail {
            get {
                return ResourceManager.GetString("G_ContactPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person tel.
        /// </summary>
        internal static string G_ContactPersonTel {
            get {
                return ResourceManager.GetString("G_ContactPersonTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact person title.
        /// </summary>
        internal static string G_ContactPersonTitle {
            get {
                return ResourceManager.GetString("G_ContactPersonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create record.
        /// </summary>
        internal static string G_Create {
            get {
                return ResourceManager.GetString("G_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create goods receving.
        /// </summary>
        internal static string G_CreateGR {
            get {
                return ResourceManager.GetString("G_CreateGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create payment.
        /// </summary>
        internal static string G_CreatePM {
            get {
                return ResourceManager.GetString("G_CreatePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PO.
        /// </summary>
        internal static string G_CreatePO {
            get {
                return ResourceManager.GetString("G_CreatePO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time.
        /// </summary>
        internal static string G_CreateTime {
            get {
                return ResourceManager.GetString("G_CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string G_Creator {
            get {
                return ResourceManager.GetString("G_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current activity.
        /// </summary>
        internal static string G_CurrentActivity {
            get {
                return ResourceManager.GetString("G_CurrentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operator.
        /// </summary>
        internal static string G_CurrentOperator {
            get {
                return ResourceManager.GetString("G_CurrentOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current step.
        /// </summary>
        internal static string G_CurrentStep {
            get {
                return ResourceManager.GetString("G_CurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string G_Delete {
            get {
                return ResourceManager.GetString("G_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date.
        /// </summary>
        internal static string G_DeliveryDate {
            get {
                return ResourceManager.GetString("G_DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery loc.
        /// </summary>
        internal static string G_DeliveryLocation {
            get {
                return ResourceManager.GetString("G_DeliveryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string G_Department {
            get {
                return ResourceManager.GetString("G_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner dept.
        /// </summary>
        internal static string G_DepartmentBelongTo {
            get {
                return ResourceManager.GetString("G_DepartmentBelongTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string G_Details {
            get {
                return ResourceManager.GetString("G_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string G_DisplayName {
            get {
                return ResourceManager.GetString("G_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document no.
        /// </summary>
        internal static string G_DocNo {
            get {
                return ResourceManager.GetString("G_DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document subject.
        /// </summary>
        internal static string G_DocSubject {
            get {
                return ResourceManager.GetString("G_DocSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        internal static string G_DocType {
            get {
                return ResourceManager.GetString("G_DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done time.
        /// </summary>
        internal static string G_DoneTime {
            get {
                return ResourceManager.GetString("G_DoneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string G_Download {
            get {
                return ResourceManager.GetString("G_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duns #.
        /// </summary>
        internal static string G_DunsNo {
            get {
                return ResourceManager.GetString("G_DunsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string G_Edit {
            get {
                return ResourceManager.GetString("G_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective date.
        /// </summary>
        internal static string G_EffectiveDate {
            get {
                return ResourceManager.GetString("G_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string G_Email {
            get {
                return ResourceManager.GetString("G_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English address.
        /// </summary>
        internal static string G_EnglishAddress {
            get {
                return ResourceManager.GetString("G_EnglishAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est cost.
        /// </summary>
        internal static string G_EstimatedCost {
            get {
                return ResourceManager.GetString("G_EstimatedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est cost(RMB).
        /// </summary>
        internal static string G_EstimatedCostInRMB {
            get {
                return ResourceManager.GetString("G_EstimatedCostInRMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp receive end.
        /// </summary>
        internal static string G_ExpectReceiveEnd {
            get {
                return ResourceManager.GetString("G_ExpectReceiveEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp receive start.
        /// </summary>
        internal static string G_ExpectReceiveStart {
            get {
                return ResourceManager.GetString("G_ExpectReceiveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string G_Fax {
            get {
                return ResourceManager.GetString("G_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First buy date.
        /// </summary>
        internal static string G_FirstBuyDate {
            get {
                return ResourceManager.GetString("G_FirstBuyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First buy memo.
        /// </summary>
        internal static string G_FirstBuyDescription {
            get {
                return ResourceManager.GetString("G_FirstBuyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First buy cost.
        /// </summary>
        internal static string G_FirstCostAmount {
            get {
                return ResourceManager.GetString("G_FirstCostAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow chart.
        /// </summary>
        internal static string G_FlowChart {
            get {
                return ResourceManager.GetString("G_FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods Receiving.
        /// </summary>
        internal static string G_GR {
            get {
                return ResourceManager.GetString("G_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index number.
        /// </summary>
        internal static string G_IndexNumber {
            get {
                return ResourceManager.GetString("G_IndexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input query conditions.
        /// </summary>
        internal static string G_InputQueryCondition {
            get {
                return ResourceManager.GetString("G_InputQueryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid.
        /// </summary>
        internal static string G_Invalid {
            get {
                return ResourceManager.GetString("G_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate.
        /// </summary>
        internal static string G_Invalidate {
            get {
                return ResourceManager.GetString("G_Invalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite opinion.
        /// </summary>
        internal static string G_InviteOther {
            get {
                return ResourceManager.GetString("G_InviteOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinions invited.
        /// </summary>
        internal static string G_InviteOtherFeedback {
            get {
                return ResourceManager.GetString("G_InviteOtherFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice #.
        /// </summary>
        internal static string G_InvoiceNo {
            get {
                return ResourceManager.GetString("G_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is advance payment.
        /// </summary>
        internal static string G_IsAdvancePayment {
            get {
                return ResourceManager.GetString("G_IsAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need bidding?.
        /// </summary>
        internal static string G_IsBidingRequired {
            get {
                return ResourceManager.GetString("G_IsBidingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default bank.
        /// </summary>
        internal static string G_IsDefaultBank {
            get {
                return ResourceManager.GetString("G_IsDefaultBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is down payment.
        /// </summary>
        internal static string G_IsDownPayment {
            get {
                return ResourceManager.GetString("G_IsDownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is first buy?.
        /// </summary>
        internal static string G_IsFirstBuy {
            get {
                return ResourceManager.GetString("G_IsFirstBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is immediate payment.
        /// </summary>
        internal static string G_IsImmediatePayment {
            get {
                return ResourceManager.GetString("G_IsImmediatePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is normal payment.
        /// </summary>
        internal static string G_IsNormalPayment {
            get {
                return ResourceManager.GetString("G_IsNormalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is published?.
        /// </summary>
        internal static string G_IsPublished {
            get {
                return ResourceManager.GetString("G_IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string G_ItemName {
            get {
                return ResourceManager.GetString("G_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item type.
        /// </summary>
        internal static string G_ItemType {
            get {
                return ResourceManager.GetString("G_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string G_Keyword {
            get {
                return ResourceManager.GetString("G_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest rate.
        /// </summary>
        internal static string G_LatestRate {
            get {
                return ResourceManager.GetString("G_LatestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string G_LineNumber {
            get {
                return ResourceManager.GetString("G_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon name.
        /// </summary>
        internal static string G_LogonName {
            get {
                return ResourceManager.GetString("G_LogonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string G_Maintain {
            get {
                return ResourceManager.GetString("G_Maintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string G_Memo {
            get {
                return ResourceManager.GetString("G_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string G_Mobile {
            get {
                return ResourceManager.GetString("G_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string G_Name {
            get {
                return ResourceManager.GetString("G_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bidding reason.
        /// </summary>
        internal static string G_NoBiddingReason {
            get {
                return ResourceManager.GetString("G_NoBiddingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available now.
        /// </summary>
        internal static string G_NotAvailableNow {
            get {
                return ResourceManager.GetString("G_NotAvailableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office phone.
        /// </summary>
        internal static string G_OfficePhone {
            get {
                return ResourceManager.GetString("G_OfficePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office phone.
        /// </summary>
        internal static string G_OfficeTel {
            get {
                return ResourceManager.GetString("G_OfficeTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Procurement Application System.
        /// </summary>
        internal static string G_OPAS {
            get {
                return ResourceManager.GetString("G_OPAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string G_Operations {
            get {
                return ResourceManager.GetString("G_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        internal static string G_OrderDate {
            get {
                return ResourceManager.GetString("G_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other contact.
        /// </summary>
        internal static string G_OtherContact {
            get {
                return ResourceManager.GetString("G_OtherContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other operations.
        /// </summary>
        internal static string G_OtherOperations {
            get {
                return ResourceManager.GetString("G_OtherOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other vendors.
        /// </summary>
        internal static string G_OtherVendorsNotInList {
            get {
                return ResourceManager.GetString("G_OtherVendorsNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing slip#.
        /// </summary>
        internal static string G_PackingSlipNo {
            get {
                return ResourceManager.GetString("G_PackingSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid time.
        /// </summary>
        internal static string G_PaidTime {
            get {
                return ResourceManager.GetString("G_PaidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string G_Password {
            get {
                return ResourceManager.GetString("G_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying in ? days.
        /// </summary>
        internal static string G_PayingDaysRequirement {
            get {
                return ResourceManager.GetString("G_PayingDaysRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay area type.
        /// </summary>
        internal static string G_PaymentAreaType {
            get {
                return ResourceManager.GetString("G_PaymentAreaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay currency type.
        /// </summary>
        internal static string G_PaymentCurrencyType {
            get {
                return ResourceManager.GetString("G_PaymentCurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay method type.
        /// </summary>
        internal static string G_PaymentMethodType {
            get {
                return ResourceManager.GetString("G_PaymentMethodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment terms.
        /// </summary>
        internal static string G_PaymentTerm {
            get {
                return ResourceManager.GetString("G_PaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private mobile.
        /// </summary>
        internal static string G_PersonalMobile {
            get {
                return ResourceManager.GetString("G_PersonalMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private phone.
        /// </summary>
        internal static string G_PersonalTel {
            get {
                return ResourceManager.GetString("G_PersonalTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string G_Phone {
            get {
                return ResourceManager.GetString("G_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose.
        /// </summary>
        internal static string G_PleaseChoose {
            get {
                return ResourceManager.GetString("G_PleaseChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO type.
        /// </summary>
        internal static string G_POType {
            get {
                return ResourceManager.GetString("G_POType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string G_Price {
            get {
                return ResourceManager.GetString("G_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string G_PurchaseOrder {
            get {
                return ResourceManager.GetString("G_PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Requisition.
        /// </summary>
        internal static string G_PurchaseRequisition {
            get {
                return ResourceManager.GetString("G_PurchaseRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string G_Quantity {
            get {
                return ResourceManager.GetString("G_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string G_Query {
            get {
                return ResourceManager.GetString("G_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string G_Reason {
            get {
                return ResourceManager.GetString("G_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received quantity.
        /// </summary>
        internal static string G_ReceivedQuantity {
            get {
                return ResourceManager.GetString("G_ReceivedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string G_Receiver {
            get {
                return ResourceManager.GetString("G_Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid register time.
        /// </summary>
        internal static string G_RegisterPaidTime {
            get {
                return ResourceManager.GetString("G_RegisterPaidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid register.
        /// </summary>
        internal static string G_RegisterPaidUser {
            get {
                return ResourceManager.GetString("G_RegisterPaidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string G_Reject {
            get {
                return ResourceManager.GetString("G_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant documents list.
        /// </summary>
        internal static string G_RelevantDocuments {
            get {
                return ResourceManager.GetString("G_RelevantDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string G_Remark {
            get {
                return ResourceManager.GetString("G_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string G_RemarkOfApprover {
            get {
                return ResourceManager.GetString("G_RemarkOfApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver remarks.
        /// </summary>
        internal static string G_RemarkOfApprovers {
            get {
                return ResourceManager.GetString("G_RemarkOfApprovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string G_Reset {
            get {
                return ResourceManager.GetString("G_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running days.
        /// </summary>
        internal static string G_RunningDays {
            get {
                return ResourceManager.GetString("G_RunningDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string G_Save {
            get {
                return ResourceManager.GetString("G_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save only.
        /// </summary>
        internal static string G_SaveTemp {
            get {
                return ResourceManager.GetString("G_SaveTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default.
        /// </summary>
        internal static string G_SetDefault {
            get {
                return ResourceManager.GetString("G_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping info.
        /// </summary>
        internal static string G_ShippingInfo {
            get {
                return ResourceManager.GetString("G_ShippingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string G_ShortName {
            get {
                return ResourceManager.GetString("G_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string G_Submit {
            get {
                return ResourceManager.GetString("G_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string G_SubmitForApproval {
            get {
                return ResourceManager.GetString("G_SubmitForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest operation.
        /// </summary>
        internal static string G_SuggestFlowConnection {
            get {
                return ResourceManager.GetString("G_SuggestFlowConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string G_Suggestion {
            get {
                return ResourceManager.GetString("G_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest operator.
        /// </summary>
        internal static string G_SuggestToNodeRole {
            get {
                return ResourceManager.GetString("G_SuggestToNodeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT code.
        /// </summary>
        internal static string G_SWIFTCode {
            get {
                return ResourceManager.GetString("G_SWIFTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string G_Symbol {
            get {
                return ResourceManager.GetString("G_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System manager.
        /// </summary>
        internal static string G_SystemManager {
            get {
                return ResourceManager.GetString("G_SystemManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total records count:.
        /// </summary>
        internal static string G_TotalRecordsCount {
            get {
                return ResourceManager.GetString("G_TotalRecordsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking #.
        /// </summary>
        internal static string G_TrackingNo {
            get {
                return ResourceManager.GetString("G_TrackingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string G_Type {
            get {
                return ResourceManager.GetString("G_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoM.
        /// </summary>
        internal static string G_UnitMeasure_Abbr {
            get {
                return ResourceManager.GetString("G_UnitMeasure_Abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files forbidden.
        /// </summary>
        internal static string G_UploadNote {
            get {
                return ResourceManager.GetString("G_UploadNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string G_User {
            get {
                return ResourceManager.GetString("G_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        internal static string G_Validation_Required {
            get {
                return ResourceManager.GetString("G_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string G_Vendor {
            get {
                return ResourceManager.GetString("G_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor bank acc#.
        /// </summary>
        internal static string G_VendorBankAccount {
            get {
                return ResourceManager.GetString("G_VendorBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor bank.
        /// </summary>
        internal static string G_VendorBankName {
            get {
                return ResourceManager.GetString("G_VendorBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor banks.
        /// </summary>
        internal static string G_VendorBanks {
            get {
                return ResourceManager.GetString("G_VendorBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor #.
        /// </summary>
        internal static string G_VendorNo {
            get {
                return ResourceManager.GetString("G_VendorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Organization #.
        /// </summary>
        internal static string G_VendorOrgNo {
            get {
                return ResourceManager.GetString("G_VendorOrgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string G_Version {
            get {
                return ResourceManager.GetString("G_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WBS no.
        /// </summary>
        internal static string G_WBSNo {
            get {
                return ResourceManager.GetString("G_WBSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string G_Weight {
            get {
                return ResourceManager.GetString("G_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Ops.
        /// </summary>
        internal static string G_WorkflowOperation {
            get {
                return ResourceManager.GetString("G_WorkflowOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - total.
        /// </summary>
        internal static string G__Total {
            get {
                return ResourceManager.GetString("G__Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese name.
        /// </summary>
        internal static string MD_ChineseName {
            get {
                return ResourceManager.GetString("MD_ChineseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string MD_CostCenter {
            get {
                return ResourceManager.GetString("MD_CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent cost center.
        /// </summary>
        internal static string MD_CostCenterParent {
            get {
                return ResourceManager.GetString("MD_CostCenterParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost element.
        /// </summary>
        internal static string MD_CostElement {
            get {
                return ResourceManager.GetString("MD_CostElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost element account type.
        /// </summary>
        internal static string MD_CostElementAccountType {
            get {
                return ResourceManager.GetString("MD_CostElementAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost element type.
        /// </summary>
        internal static string MD_CostElementType {
            get {
                return ResourceManager.GetString("MD_CostElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency rate.
        /// </summary>
        internal static string MD_CurrencyRate {
            get {
                return ResourceManager.GetString("MD_CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency type.
        /// </summary>
        internal static string MD_CurrencyType {
            get {
                return ResourceManager.GetString("MD_CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MD_Description {
            get {
                return ResourceManager.GetString("MD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        internal static string MD_EnglishName {
            get {
                return ResourceManager.GetString("MD_EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function permissions.
        /// </summary>
        internal static string MD_FunctionPermission {
            get {
                return ResourceManager.GetString("MD_FunctionPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string MD_Number {
            get {
                return ResourceManager.GetString("MD_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost centers.
        /// </summary>
        internal static string MENU_CostCenters {
            get {
                return ResourceManager.GetString("MENU_CostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost elements.
        /// </summary>
        internal static string MENU_CostElements {
            get {
                return ResourceManager.GetString("MENU_CostElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost element types.
        /// </summary>
        internal static string MENU_CostElementTypes {
            get {
                return ResourceManager.GetString("MENU_CostElementTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency rates.
        /// </summary>
        internal static string MENU_CurrencyRates {
            get {
                return ResourceManager.GetString("MENU_CurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string MENU_CurrencyTypes {
            get {
                return ResourceManager.GetString("MENU_CurrencyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegations.
        /// </summary>
        internal static string MENU_Delegation {
            get {
                return ResourceManager.GetString("MENU_Delegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string MENU_Departments {
            get {
                return ResourceManager.GetString("MENU_Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective POs.
        /// </summary>
        internal static string MENU_EffectivePOs {
            get {
                return ResourceManager.GetString("MENU_EffectivePOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective PRs.
        /// </summary>
        internal static string MENU_EffectivePRs {
            get {
                return ResourceManager.GetString("MENU_EffectivePRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string MENU_FlowInstancesMgmt {
            get {
                return ResourceManager.GetString("MENU_FlowInstancesMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow definition.
        /// </summary>
        internal static string MENU_FlowTemplates {
            get {
                return ResourceManager.GetString("MENU_FlowTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad-Hoc Query.
        /// </summary>
        internal static string MENU_FreeQuery {
            get {
                return ResourceManager.GetString("MENU_FreeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR.
        /// </summary>
        internal static string MENU_GR {
            get {
                return ResourceManager.GetString("MENU_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MENU_Help {
            get {
                return ResourceManager.GetString("MENU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval history.
        /// </summary>
        internal static string MENU_History {
            get {
                return ResourceManager.GetString("MENU_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon.
        /// </summary>
        internal static string MENU_Logon {
            get {
                return ResourceManager.GetString("MENU_Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MENU_Logout {
            get {
                return ResourceManager.GetString("MENU_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master data.
        /// </summary>
        internal static string MENU_MDM {
            get {
                return ResourceManager.GetString("MENU_MDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string MENU_Messages {
            get {
                return ResourceManager.GetString("MENU_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MENU_MY {
            get {
                return ResourceManager.GetString("MENU_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My applications.
        /// </summary>
        internal static string MENU_MyApplications {
            get {
                return ResourceManager.GetString("MENU_MyApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept applications .
        /// </summary>
        internal static string MENU_MyDepartmentApplications {
            get {
                return ResourceManager.GetString("MENU_MyDepartmentApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MENU_New {
            get {
                return ResourceManager.GetString("MENU_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string MENU_Permission {
            get {
                return ResourceManager.GetString("MENU_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string MENU_PM {
            get {
                return ResourceManager.GetString("MENU_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO/Contract.
        /// </summary>
        internal static string MENU_PO {
            get {
                return ResourceManager.GetString("MENU_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        internal static string MENU_PR {
            get {
                return ResourceManager.GetString("MENU_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MENU_Report {
            get {
                return ResourceManager.GetString("MENU_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string MENU_Roles {
            get {
                return ResourceManager.GetString("MENU_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string MENU_SysManage {
            get {
                return ResourceManager.GetString("MENU_SysManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MENU_Users {
            get {
                return ResourceManager.GetString("MENU_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string MENU_Vendors {
            get {
                return ResourceManager.GetString("MENU_Vendors", resourceCulture);
            }
        }
    }
}
